### ISSUE TITLE
 Could not interpret optimizer identifier

### ISSUE THREAD

**Issue by amanramanandsharma** [Rizo-R/chess-cv#1]
Traceback (most recent call last):
  File "C:\Users\Aman_CareEco\Downloads\chess-cv\main.py", line 21, in <module>
    from preprocess import preprocess_image
  File "C:\Users\Aman_CareEco\Downloads\chess-cv\preprocess.py", line 12, in <module>
    from laps import LAPS
  File "C:\Users\Aman_CareEco\Downloads\chess-cv\laps.py", line 4, in <module>
    import deps
  File "C:\Users\Aman_CareEco\Downloads\chess-cv\deps\__init__.py", line 2, in <module>
    from . import laps
  File "C:\Users\Aman_CareEco\Downloads\chess-cv\deps\laps.py", line 24, in <module>
    model.compile(RMSProp(learning_rate=0.001),
  File "C:\Users\Aman_CareEco\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Aman_CareEco\anaconda3\lib\site-packages\keras\optimizers\__init__.py", line 230, in get
    raise ValueError(
**ValueError: Could not interpret optimizer identifier: <tensorflow.python.keras.optimizer_v2.rmsprop.RMSprop object at 0x00000178798D2D30>**

**Comment by raulsenaferreira** [comment]
Use ``from tensorflow.keras.optimizers import RMSprop" instead
